name: CI
on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7.6']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Update RubyGems and install dependencies
        run: |
          gem update --system 3.3.22
          bundle config set --local force_ruby_platform true
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        run: bundle exec rspec

      - name: Rubocop
        run: bundle exec rubocop